version: "3.9"

services:

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    expose:
      - 5672
    networks:
        - web 
  gateway:
    build: ./backend/gateway
    image: gateway-image
    container_name: gateway
    ports:
      - "4000:4000"
    networks:
        - web
    volumes:
        - ./frontend:/var/www/html/frontend
  user:
    build: ./backend/services/user
    image: user-image
    container_name: user
    command: sh -c "npx prisma migrate dev --name init && npm run start "
    networks: 
        - web
  auth:
    build: ./backend/services/auth
    image: auth-image
    container_name: auth
    networks:
        - web


networks:
  web:
    driver: bridge

  