version: "3.9"

services:
  user:
    build: ../backend/services/user
    image: user-image
    container_name: user-service
    ports:
      - "4000:4000"
    networks:
        - inception
    volumes:
        - ../frontend:/var/www/html/frontend


networks:
  inception:
    driver: bridge

  